### PR TITLE
User defaults bug fix

### LINKED ISSUE #125: App crashing when a user tries to log back in
When a user had been previously logged in, after they log out and try to log back in the app crashes.

### PR DESCRIPTION
**Pull request by PhyllisWong**
closes #125 
App was crashing when a user had been logged in, then logged out, and tried to log back in. The crash was that MyTrips View Controller was calling the setupUserDataDisplay() function was being called by viewDidLoad before the check if user was logged in. Now the call for user data happens after a logged in user has been identified.

### CODE REVIEW

File: Breezy-Traveler/UserModel.swift [hunk 1]
```diff
@@ -18,6 +18,8 @@ struct BTUser: Codable {
     static func getStoredUser() -> BTUser {
         let userPersistence = UserPersistence()
         guard let currentUser = userPersistence.getCurrentUser() else {
+            
+            // FIXME: crashing the app
```
Comment (LinnierGames) [inline Breezy-Traveler/UserModel.swift]: I wouldn't think this needs a fix me. this `getStoredUser()` should never be called without checking if a user is logged in.
